remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
google_analytics: G-WKXW4SYK2D
title: Airflow Made Easy | Local Setup Using Docker
description: Here, we guide you step-by-step on setting up Airflow locally with Docker. Simplify your workflow and explore our easy-to-follow instructions for seamless Airflow deployment on your machine.
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - COVID_NY.md
