version: '3'

services:
  # Worker that listens to the youtube queue
  airflow-worker-youtube:
    build:
      context: .
      dockerfile: worker.dockerfile
    restart: always
    container_name: airflow-worker-youtube
    user: "0"  # Start as root user to allow permission fixes
    environment:
      AIRFLOW__CORE__HOSTNAME_CALLABLE: 'airflow.utils.net.get_host_ip_address'
      # Specify which queues this worker should process
      AIRFLOW__CELERY__DEFAULT_QUEUE: 'youtube'
      AIRFLOW__CELERY__WORKER_CONCURRENCY: 2
      AIRFLOW_CONN_METADATA_DB: 'postgres://airflow:airflow@172.29.25.15:5433/airflow'
      # Listen only to youtube queue
      AIRFLOW__CELERY__CELERY_QUEUES: 'youtube'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    command: airflow celery worker -q youtube
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 30s
      retries: 10 