# This is a basic workflow to help you get started with Actions

name: Execute Airflow Unit Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths: 
      - 'dags/**'
      - 'pg-init-scripts/**'
      - 'sql/**'
      - 'test/**'
      - '!README.md'
      - '!COVID_NY.md'

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create directories
        run: mkdir ./logs ./plugins

      - name: Remove .env file
        run: rm -f .env

      - name: Change Permission
        run: |
          sudo chmod u=rwx,g=rwx,o=rwx ./dags
          sudo chmod u=rwx,g=rwx,o=rwx ./logs
          sudo chmod u=rwx,g=rwx,o=rwx ./sql
          sudo chmod u=rwx,g=rwx,o=rwx ./test
          sudo chmod u=rwx,g=rwx,o=rwx ./pg-init-scripts

     # Runs a single command using the runners shell
      - name: Create Airflow environment
        run: make setup

      # Runs a set of commands using the runners shell
      - name: Execute Airflow Tests
        run: make testing
