# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Dump UID & GID
        run: |
          echo User ID [UID]: $(id -u)
          echo Group ID [GID]: $(id -g)
      - name: Setup Env file
        run: |
          export AIRFLOW_UID=1001
          export AIRFLOW_GID=116
      - name: Setup Env file
        run: echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=$(id -g)" > .env
      - name: Print Env file
        run: cat .env
      # Runs a single command using the runners shell
      - name: Create Airflow environment
        run: make setup

      # Runs a set of commands using the runners shell
      - name: Execute Airflow Tests
        run: make testing
          echo Add other actions to build,
          echo test, and deploy your project.
